---
# section for vars
shell_profiles:
- .bash_profile

# version variables
tpm2_tss_version: a0d6f7d
tpm2_tools_version: master
tpm2_abrmd_version: master

# configure arguments
tpm2_tss_configure_args: "./configure --prefix=/usr --disable-doxygen-doc"
tmp2_tools_configure_args: "TSS2_SYS_CFLAGS=' ' TSS2_SYS_LIBS='-ltss2-sys -L/usr/lib/' ./configure --prefix=/usr/local"
tpm2_abrmd_configure_args: "SAPI_CFLAGS=' ' SAPI_LIBS='-ltss2-sys -L/usr/lib/' ./configure --prefix=/usr"

