# must be root to execute this task

# INSTALL tpm2-tss
- name: /bootstrap tpm software stack (tss)
  command: ./bootstrap
  args:
      chdir: /root/tpm2-tss

- name: /configure tpm software stack (tss)
  command: "{{ tpm2_tss_configure_args }}"    
  args:
      chdir: /root/tpm2-tss

- name: compile tpm software stack (tss)
  make:
      chdir: /root/tpm2-tss

- name: install tpm software stack (tss)
  make:
      chdir: /root/tpm2-tss
      target: install


# INSTALL tpm2-tools
- name: /bootstrap tpm tools (tools)
  command: ./bootstrap
  args:
      chdir: /root/tpm2-tools

- name: /configure tpm tools (tools)
  command: "{{ tpm2_tools_configure_args }}" 
  args:
      chdir: /root/tpm2-tools

- name: compile tpm tools (tools)
  make:
      chdir: /root/tpm2-tools

- name: install tpm tools (tools)
  make:
      chdir: /root/tpm2-tools
      target: install


# INSTALL tpm2-abrmd
- name: /bootstrap tpm resource manage (abrmd)
  command: ./bootstrap
  args:
      chdir: /root/tpm2-abrmd

- name: /configure tpm resource mamager (abrmd)
  command: "{{ tpm2_abrmd_configure_args }}" 
  args:
      chdir: /root/tpm2-abrmd

- name: compile tpm resource manager (abrmd)
  make:
      chdir: /root/tpm2-abrmd

- name: install tpm resource manager (abrmd)
  make:
      chdir: /root/tpm2-abrmd
      target: install

- name: ldconfig
  command: ldconfig
  args:
      chdir: /root/tpm2-abrmd
